### ISSUE TITLE
Update for Elm 0.19.1

### ISSUE THREAD

**Issue by malaire** [justinmimbs/timezone-json#2]
Just changing `elm-version` to `0.19.1`in `elm.json` isn't enough.

Running `build.sh` after that gives `UNEXPECTED FILE NAME` error for `tests/compare/Main.elm`.

**Comment by justinmimbs** [comment]
Hi Markus,

I updated for Elm 0.19.1 and `elm/http` 2.0.0. Please let me know if you have any trouble.

This project was an experiment before `elm/bytes` existed. If you're looking to serve time zones now, then I would take a look at [serving TZif files](https://github.com/justinmimbs/tzif) instead of JSON.

Thanks,

Justin

**Comment by malaire** [comment]
Thanks, I didn't know about that other project. I came to this project because this is recommended by timezone-data at [1].

[1] https://package.elm-lang.org/packages/justinmimbs/timezone-data/latest/

**Comment by justinmimbs** [comment]
Ah, thank you! I will update that link.
